Merge original README
martukas/nuclei pull request #15
Opened 2023-06-13 10:44 UTC by ferdymercury

Fixes https://github.com/martukas/nuclei/issues/7

2024-02-02 08:26 UTC, martukas requested changes
Thanks! Sorry it took a while to respond to this.
I have provided a few suggestions.

2024-02-02 08:26 UTC, martukas commented on README.md
> +Nuclei is a software tool for the displaying of nuclear decay schemes and estimated energy spectra, the calculation of angular γ emission anisotropies, and the automated search for appropriate decay
I am uncertain if that's still true. In my modernization, I think I removed the sprectra generation feature.

2024-02-02 08:26 UTC, martukas commented on README.md
> +sudo apt install libqt5svg5-dev
I might even simplify this `Building` section with simply a pointer to the circleci script to see what packages are installed. What bulids on CI is the closest thing to a guarantee of functionality. Everything else is hard to state with any certainty and/or maintain.

2024-02-02 08:26 UTC, martukas commented on README.md
> +© 2012-2013, Matthias Nagl, II. Physikalisches Institut, Georg-August-Universität Göttingen
Probably the old license no longer applies? Also, the specific link is dead and just goes to the institute's main page. Maybe we don't need this snippet?

2024-02-02 10:31 UTC, martukas approved these changes
LGTM

2024-02-13 12:00 UTC, ferdymercury commented
@php1ic it seems that the circleci does not run well. Could it maybe be a multithreading issue?

2024-02-13 12:51 UTC, php1ic commented
Yeah, I have seen this before on circleci, sometimes the build fails if you let things build without specifying how many cores/threads to use.

https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-build-j

Simplest way is to add an argument after `--parallel` on [line 27](https://github.com/martukas/nuclei/blob/main/.circleci/config.yml#L27) of the config file. Looks like it uses a 2 core CPU so that is the number we should use.

2024-02-13 19:36 UTC, merged